/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#7ddb8a",
        "tertiary-fixed-dim": "#b7c8de",
        "surface-bright": "#fbf9f9",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#38485a",
        "inverse-on-surface": "#f2f0f0",
        "on-surface": "#1b1c1c",
        "surface-variant": "#e3e2e2",
        "secondary-fixed": "#ffdad6",
        "surface-container-highest": "#e3e2e2",
        "surface-container-low": "#f5f3f3",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#7e2a25",
        "on-secondary-fixed-variant": "#5d3f3c",
        "error": "#ba1a1a",
        "outline": "#777777",
        "secondary-container": "#ffdad6",
        "surface-dim": "#dbdad9",
        "on-primary": "#ffffff",
        "surface": "#fbf9f9",
        "surface-container-high": "#e9e8e7",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#474747",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#fedfa5",
        "on-secondary-container": "#5d3f3c",
        "on-secondary-fixed": "#2c1513",
        "inverse-primary": "#ffb4ac",
        "on-tertiary-fixed": "#261900",
        "on-background": "#1b1c1c",
        "secondary": "#775653",
        "primary-container": "#ffdad6",
        "inverse-surface": "#303031",
        "on-primary-fixed": "#410003",
        "outline-variant": "#c6c6c6",
        "tertiary": "#715b2e",
        "primary-fixed": "#ffdad6",
        "surface-tint": "#9d413b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#584419",
        "surface-container": "#efeded",
        "background": "#fbf9f9",
        "tertiary-container": "#fedfa5",
        "on-primary-container": "#7e2a25",
        "primary": "#9d413b",
        "primary-fixed-dim": "#ffb4ac"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "lg": "40px",
        "md": "24px",
        "gutter": "16px",
        "margin-desktop": "48px",
        "xl": "64px",
        "margin-mobile": "20px",
        "xs": "4px",
        "sm": "12px"
      },
      fontFamily: {
        "body-md": ["Public Sans"],
        "label-lg": ["Public Sans"],
        "body-lg": ["Public Sans"],
        "headline-sm": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "label-sm": ["Public Sans"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
