/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedSolicitacoesRouteImport } from './routes/_authenticated.solicitacoes'
import { Route as AuthenticatedSincronizacaoRouteImport } from './routes/_authenticated.sincronizacao'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated.historico'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedRelatorioIdRouteImport } from './routes/_authenticated.relatorio.$id'
import { Route as AuthenticatedInspecaoNovaRouteImport } from './routes/_authenticated.inspecao.nova'
import { Route as AuthenticatedInspecaoIdResultadoRouteImport } from './routes/_authenticated.inspecao.$id.resultado'
import { Route as AuthenticatedInspecaoIdQrRouteImport } from './routes/_authenticated.inspecao.$id.qr'
import { Route as AuthenticatedInspecaoIdPreviewIaRouteImport } from './routes/_authenticated.inspecao.$id.preview-ia'
import { Route as AuthenticatedInspecaoIdObservacoesRouteImport } from './routes/_authenticated.inspecao.$id.observacoes'
import { Route as AuthenticatedInspecaoIdAnalisandoRouteImport } from './routes/_authenticated.inspecao.$id.analisando'
import { Route as AuthenticatedInspecaoIdSetorSidRouteImport } from './routes/_authenticated.inspecao.$id.setor.$sid'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSolicitacoesRoute =
  AuthenticatedSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSincronizacaoRoute =
  AuthenticatedSincronizacaoRouteImport.update({
    id: '/sincronizacao',
    path: '/sincronizacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatorioIdRoute =
  AuthenticatedRelatorioIdRouteImport.update({
    id: '/relatorio/$id',
    path: '/relatorio/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInspecaoNovaRoute =
  AuthenticatedInspecaoNovaRouteImport.update({
    id: '/inspecao/nova',
    path: '/inspecao/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInspecaoIdResultadoRoute =
  AuthenticatedInspecaoIdResultadoRouteImport.update({
    id: '/inspecao/$id/resultado',
    path: '/inspecao/$id/resultado',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInspecaoIdQrRoute =
  AuthenticatedInspecaoIdQrRouteImport.update({
    id: '/inspecao/$id/qr',
    path: '/inspecao/$id/qr',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInspecaoIdPreviewIaRoute =
  AuthenticatedInspecaoIdPreviewIaRouteImport.update({
    id: '/inspecao/$id/preview-ia',
    path: '/inspecao/$id/preview-ia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInspecaoIdObservacoesRoute =
  AuthenticatedInspecaoIdObservacoesRouteImport.update({
    id: '/inspecao/$id/observacoes',
    path: '/inspecao/$id/observacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInspecaoIdAnalisandoRoute =
  AuthenticatedInspecaoIdAnalisandoRouteImport.update({
    id: '/inspecao/$id/analisando',
    path: '/inspecao/$id/analisando',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInspecaoIdSetorSidRoute =
  AuthenticatedInspecaoIdSetorSidRouteImport.update({
    id: '/inspecao/$id/setor/$sid',
    path: '/inspecao/$id/setor/$sid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/sincronizacao': typeof AuthenticatedSincronizacaoRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/inspecao/nova': typeof AuthenticatedInspecaoNovaRoute
  '/relatorio/$id': typeof AuthenticatedRelatorioIdRoute
  '/inspecao/$id/analisando': typeof AuthenticatedInspecaoIdAnalisandoRoute
  '/inspecao/$id/observacoes': typeof AuthenticatedInspecaoIdObservacoesRoute
  '/inspecao/$id/preview-ia': typeof AuthenticatedInspecaoIdPreviewIaRoute
  '/inspecao/$id/qr': typeof AuthenticatedInspecaoIdQrRoute
  '/inspecao/$id/resultado': typeof AuthenticatedInspecaoIdResultadoRoute
  '/inspecao/$id/setor/$sid': typeof AuthenticatedInspecaoIdSetorSidRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/sincronizacao': typeof AuthenticatedSincronizacaoRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/': typeof AuthenticatedIndexRoute
  '/inspecao/nova': typeof AuthenticatedInspecaoNovaRoute
  '/relatorio/$id': typeof AuthenticatedRelatorioIdRoute
  '/inspecao/$id/analisando': typeof AuthenticatedInspecaoIdAnalisandoRoute
  '/inspecao/$id/observacoes': typeof AuthenticatedInspecaoIdObservacoesRoute
  '/inspecao/$id/preview-ia': typeof AuthenticatedInspecaoIdPreviewIaRoute
  '/inspecao/$id/qr': typeof AuthenticatedInspecaoIdQrRoute
  '/inspecao/$id/resultado': typeof AuthenticatedInspecaoIdResultadoRoute
  '/inspecao/$id/setor/$sid': typeof AuthenticatedInspecaoIdSetorSidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/sincronizacao': typeof AuthenticatedSincronizacaoRoute
  '/_authenticated/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/inspecao/nova': typeof AuthenticatedInspecaoNovaRoute
  '/_authenticated/relatorio/$id': typeof AuthenticatedRelatorioIdRoute
  '/_authenticated/inspecao/$id/analisando': typeof AuthenticatedInspecaoIdAnalisandoRoute
  '/_authenticated/inspecao/$id/observacoes': typeof AuthenticatedInspecaoIdObservacoesRoute
  '/_authenticated/inspecao/$id/preview-ia': typeof AuthenticatedInspecaoIdPreviewIaRoute
  '/_authenticated/inspecao/$id/qr': typeof AuthenticatedInspecaoIdQrRoute
  '/_authenticated/inspecao/$id/resultado': typeof AuthenticatedInspecaoIdResultadoRoute
  '/_authenticated/inspecao/$id/setor/$sid': typeof AuthenticatedInspecaoIdSetorSidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/historico'
    | '/onboarding'
    | '/sincronizacao'
    | '/solicitacoes'
    | '/inspecao/nova'
    | '/relatorio/$id'
    | '/inspecao/$id/analisando'
    | '/inspecao/$id/observacoes'
    | '/inspecao/$id/preview-ia'
    | '/inspecao/$id/qr'
    | '/inspecao/$id/resultado'
    | '/inspecao/$id/setor/$sid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/historico'
    | '/onboarding'
    | '/sincronizacao'
    | '/solicitacoes'
    | '/'
    | '/inspecao/nova'
    | '/relatorio/$id'
    | '/inspecao/$id/analisando'
    | '/inspecao/$id/observacoes'
    | '/inspecao/$id/preview-ia'
    | '/inspecao/$id/qr'
    | '/inspecao/$id/resultado'
    | '/inspecao/$id/setor/$sid'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/historico'
    | '/_authenticated/onboarding'
    | '/_authenticated/sincronizacao'
    | '/_authenticated/solicitacoes'
    | '/_authenticated/'
    | '/_authenticated/inspecao/nova'
    | '/_authenticated/relatorio/$id'
    | '/_authenticated/inspecao/$id/analisando'
    | '/_authenticated/inspecao/$id/observacoes'
    | '/_authenticated/inspecao/$id/preview-ia'
    | '/_authenticated/inspecao/$id/qr'
    | '/_authenticated/inspecao/$id/resultado'
    | '/_authenticated/inspecao/$id/setor/$sid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solicitacoes': {
      id: '/_authenticated/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof AuthenticatedSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sincronizacao': {
      id: '/_authenticated/sincronizacao'
      path: '/sincronizacao'
      fullPath: '/sincronizacao'
      preLoaderRoute: typeof AuthenticatedSincronizacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorio/$id': {
      id: '/_authenticated/relatorio/$id'
      path: '/relatorio/$id'
      fullPath: '/relatorio/$id'
      preLoaderRoute: typeof AuthenticatedRelatorioIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspecao/nova': {
      id: '/_authenticated/inspecao/nova'
      path: '/inspecao/nova'
      fullPath: '/inspecao/nova'
      preLoaderRoute: typeof AuthenticatedInspecaoNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspecao/$id/resultado': {
      id: '/_authenticated/inspecao/$id/resultado'
      path: '/inspecao/$id/resultado'
      fullPath: '/inspecao/$id/resultado'
      preLoaderRoute: typeof AuthenticatedInspecaoIdResultadoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspecao/$id/qr': {
      id: '/_authenticated/inspecao/$id/qr'
      path: '/inspecao/$id/qr'
      fullPath: '/inspecao/$id/qr'
      preLoaderRoute: typeof AuthenticatedInspecaoIdQrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspecao/$id/preview-ia': {
      id: '/_authenticated/inspecao/$id/preview-ia'
      path: '/inspecao/$id/preview-ia'
      fullPath: '/inspecao/$id/preview-ia'
      preLoaderRoute: typeof AuthenticatedInspecaoIdPreviewIaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspecao/$id/observacoes': {
      id: '/_authenticated/inspecao/$id/observacoes'
      path: '/inspecao/$id/observacoes'
      fullPath: '/inspecao/$id/observacoes'
      preLoaderRoute: typeof AuthenticatedInspecaoIdObservacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspecao/$id/analisando': {
      id: '/_authenticated/inspecao/$id/analisando'
      path: '/inspecao/$id/analisando'
      fullPath: '/inspecao/$id/analisando'
      preLoaderRoute: typeof AuthenticatedInspecaoIdAnalisandoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspecao/$id/setor/$sid': {
      id: '/_authenticated/inspecao/$id/setor/$sid'
      path: '/inspecao/$id/setor/$sid'
      fullPath: '/inspecao/$id/setor/$sid'
      preLoaderRoute: typeof AuthenticatedInspecaoIdSetorSidRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSincronizacaoRoute: typeof AuthenticatedSincronizacaoRoute
  AuthenticatedSolicitacoesRoute: typeof AuthenticatedSolicitacoesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInspecaoNovaRoute: typeof AuthenticatedInspecaoNovaRoute
  AuthenticatedRelatorioIdRoute: typeof AuthenticatedRelatorioIdRoute
  AuthenticatedInspecaoIdAnalisandoRoute: typeof AuthenticatedInspecaoIdAnalisandoRoute
  AuthenticatedInspecaoIdObservacoesRoute: typeof AuthenticatedInspecaoIdObservacoesRoute
  AuthenticatedInspecaoIdPreviewIaRoute: typeof AuthenticatedInspecaoIdPreviewIaRoute
  AuthenticatedInspecaoIdQrRoute: typeof AuthenticatedInspecaoIdQrRoute
  AuthenticatedInspecaoIdResultadoRoute: typeof AuthenticatedInspecaoIdResultadoRoute
  AuthenticatedInspecaoIdSetorSidRoute: typeof AuthenticatedInspecaoIdSetorSidRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSincronizacaoRoute: AuthenticatedSincronizacaoRoute,
  AuthenticatedSolicitacoesRoute: AuthenticatedSolicitacoesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInspecaoNovaRoute: AuthenticatedInspecaoNovaRoute,
  AuthenticatedRelatorioIdRoute: AuthenticatedRelatorioIdRoute,
  AuthenticatedInspecaoIdAnalisandoRoute:
    AuthenticatedInspecaoIdAnalisandoRoute,
  AuthenticatedInspecaoIdObservacoesRoute:
    AuthenticatedInspecaoIdObservacoesRoute,
  AuthenticatedInspecaoIdPreviewIaRoute: AuthenticatedInspecaoIdPreviewIaRoute,
  AuthenticatedInspecaoIdQrRoute: AuthenticatedInspecaoIdQrRoute,
  AuthenticatedInspecaoIdResultadoRoute: AuthenticatedInspecaoIdResultadoRoute,
  AuthenticatedInspecaoIdSetorSidRoute: AuthenticatedInspecaoIdSetorSidRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
